name: aviapoint
description: service or pilot.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^10.0.0
  bloc_concurrency: ^0.3.0
  dio: ^5.8.0+1
  expandable: ^5.0.1
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.4
  firebase_analytics: ^12.0.4
  firebase_messaging: ^16.0.4
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  flutter_widget_from_html: ^0.17.1
  freezed_annotation: ^3.1.0
  intl: any
  json_annotation: ^4.9.0
  mask_text_input_formatter: ^2.9.0
  geolocator: ^14.0.1
  percent_indicator: ^4.2.4
  provider: ^6.0.2
  share_plus: ^12.0.1
  shared_preferences: ^2.0.13
  syncfusion_flutter_pdfviewer: ^31.2.10
  path_provider: ^2.0.11
  permission_handler: ^12.0.1
  file_saver: ^0.3.1
  url_launcher: ^6.3.0
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0
  auto_size_text: ^3.0.0
  socket_io_client: ^3.0.2
  modal_bottom_sheet: ^2.1.2
  mask: ^1.0.5
  pinput: ^5.0.1
  dropdown_button2: ^2.1.4
  image_picker: ^1.0.0
  another_flushbar: ^1.12.29
  calendar_date_picker2: ^2.0.1
  dotted_border: ^3.1.0
  file_picker: ^10.3.6
  path: ^1.8.2
  flutter_slidable: ^4.0.0
  keyboard_dismisser: ^3.0.0
  semicircle_indicator: ^1.1.1
  expandable_widgets: ^1.0.3+1
  shimmer_animation: ^2.2.1
  pretty_dio_logger: ^1.3.1
  flutter_app_badge: ^2.0.2
  scrollable_positioned_list: ^0.3.8
  flutter_stories: ^0.3.1
  cached_network_image: ^3.4.1
  flutter_instagram_storyboard: ^1.0.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  google_fonts: ^6.2.0
  # app_settings: ^5.2.0
  card_swiper: ^3.0.1
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.0
  collection: ^1.18.0
  retrofit: ^4.4.1
  #flutter_widget_from_html: ^0.15.2
  url_strategy: ^0.3.0
  animated_text_kit: ^4.2.2
  meta_seo: ^3.0.9
  onesignal_flutter: ^5.2.9
  currency_text_input_formatter: ^2.2.5
  flutter_screenutil: ^5.9.3
  namefully: ^0.2.1
  flutter_typeahead: ^5.2.0
  flutter_sticky_header: ^0.8.0
  cached_video_player_plus: ^4.0.4
  flutter_carousel_slider: ^1.1.0
  video_player: ^2.9.3
  flutter_cache_manager: ^3.4.1
  gradient_borders: ^1.0.1
  visibility_detector: ^0.4.0+2
  get_it: ^9.0.5
  auto_animated: ^3.2.0
  easy_localization: ^3.0.7+1
  flutter_html: ^3.0.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  talker: ^5.0.2
  talker_flutter: ^5.0.2

#dart run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  build_runner: ^2.4.11
  #dart_code_metrics: ^5.7.5
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  intl_utils: ^2.6.1
  json_serializable: ^6.1.5
  mockito: ^5.1.0
  retrofit_generator: ^10.1.4
  auto_route_generator: ^10.0.1
  flutter_launcher_icons: ^0.14.4
  easy_sidemenu: ^0.7.1
  drift_dev: ^2.29.0
  talker_bloc_logger: ^5.0.2

onesignal_flutter:
  git:
    url: https://github.com/OneSignal/OneSignal-Flutter-SDK.git
    ref: "df09f09c754e93438bbe3975f12f2f4649f81cd3"
# Временное решение, потом надо обновить пакет modal_bottom_sheet когда пофиксят чтоб прила собаралсь и удалить dependency_overrides:
dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path_android: "assets/logo/android_logo.png"
  image_path_ios: "assets/logo/ios_logo.png"
  adaptive_icon_foreground: "assets/logo/android_logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/gif/
    - assets/mp4/
    - assets/translations/
    - assets/logo/

  fonts:
    - family: Geologica
      fonts:
        - asset: assets/fonts/geologica/Geologica-Regular.ttf
        - asset: assets/fonts/geologica/Geologica-Bold.ttf
        - asset: assets/fonts/geologica/Geologica-Medium.ttf
        - asset: assets/fonts/geologica/Geologica-Light.ttf
        - asset: assets/fonts/geologica/Geologica-Semibold.ttf
        - asset: assets/fonts/geologica/Geologica-Thin.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ru
  arb_dir: lib/l10n
  output_dir: lib/generated
